### ISSUE TITLE
Add maven assembly plugin to pom.xml

### ISSUE THREAD

**Issue by nikortel-digia** [vrk-kpa/roles-auths-client#9]
Please include Maven assembly plugin in pom.xml. This will allow creation of a client jar that includes all the dependencies. This is useful in legacy cases where Maven is not used.

Add following definition into the build plugins section 
```
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
```

Single assembly can be created:
`mvn package assembly:single` produces both roles-auths-client.jar and roles-auths-client-jar-with-dependencies.jar

This has no effect on builds that do not specify assembly:single

**Comment by mtomperi** [comment]
Added requested plugin.
